
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - "8080:8080"
        volumes:
            - F:/dev/DebOps/Jenkins/jenkins_home:/var/jenkins_home:/var/jenkins_home
        networks:
            - net
    remote-host:
        image: remote-host
        container_name: remote-host
        build:
            context: ubuntu
        networks:
            - net
networks:
    net: